### PR TITLE
Support spaces

### PR DESCRIPTION
**Pull request by yozhikoff**

### CODE REVIEW

**Comment by yozhikoff** [comment]
Sorry, misclicked

**Comment by jithu7432** [comment]
Its okay!, BTW have you tried the cython version?

**Comment by yozhikoff** [comment]
@jithu7432 just tried it - looks quite impressive!
I have a notebook with more than 300k warning messages (don't ask....) and the previous version struggled to open it, while the new one opens it slowly, but smoothly. 

However, it was a bit challenging to install it. Some suggestions / just notes
1) In my system (Ubuntu 18.04) `/usr/bin/pip` is for `Python 2`. Maybe use `/usr/bin/pip3`? Or even `python3 -m pip`, which is the recommended way of using pip now, if I remember correctly.
2) I'd also add `set -e` into the installation script. Now it applies `mv` even if something fails, making it impossible to re-run it, because the files were moved. And at the end it prints `Installation successful`, which is a bit confusing.  Maybe even add `set -e` and change `mv` to `cp`.
3) I had to link `lpython3.6m` instead of `lpython3.6` - no idea how it works, but it took me quite a while to find the solution.

Also, there is a little issue with the icon (which is quite neat btw) - in the `.desktop` file its location is stated as `Icon=/opt/notebook.ico` instead of `Icon=/opt/nbv/notebook.ico`.


And finally some minor UI issues:
1) The application window is pretty small (could it be a 4K monitor issue?)
2) The scale is also a bit small-ish, I need to increase it by 50% to more to be able to actually read the code.

**Comment by jithu7432** [comment]
Thank you for the suggestions, please try the new version.
- Added pip3
- Removed all the mv commands
- Didn't go after `set -e`, cause I don't know bash scripting.
- Regarding the `-lpython`, can't seem to find much about it anywhere, I have raised a Q at stackoverflow.
- Fixed the icon.
- Maximised the window.
- Could'nt find the API for scaling, you need to scroll holding the `ctrl` key to adjust the scale.

**Comment by yozhikoff** [comment]
@jithu7432 

- `set -e` thing is something very simple, just add it to the header of installation script and it will stop after first error, otherwise it will continue executing lines. Like this: 
```bash
#!/bin/bash
set -e
END="/opt/nbv/"
``` 

- In my system (Ubuntu 18.04) default python is 2.7, so I had to slightly change the `python-config` part
``` bash
gcc -Os `python3-config --includes` notebook.c -l$PYTHON -o notebook

```

- Regarding scaling, if you use `QWebEnginePage` class there is a `setZoomFactor()` method. But I don't know if there's a good way of dynamically determining scale factor for each monitor in advance.


In general, everything works fine!

**Comment by jithu7432** [comment]
* Added `set -e`
* Changed the `python-config` to use `python3`
* Added a zoom factor of 110%, can change the default value in the source code (see comments in the src) 
* Also can adjust the zoomfactor using the `crtl` key and mouse.

**Pull request closed without merging**
